# Generated by Django 5.0.1 on 2024-02-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_address_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_sts',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
